language: python
python:
  - "3.8"
services:
  - docker

before_install:
  - docker build -t mutants -f Dockerfile-dev .

install:
  - pip install coveralls

script:
  - docker run -v $(pwd):/app/ mutants /bin/bash -c "mypy && pytest --cov=flaskr --cov-report=xml && flake8"

after_success:
  - mv .coverage .coverage.docker
  - coverage combine
  - coveralls

before_deploy:
  - pip install awscli

deploy:
  provider: script
  script: scripts/build_and_push_image.sh
  on:
    branch: master

env:
  global:
    - secure: XV6g7N4fAgP/neeI3SfEXgTvA7BJ0VdS+07E9schruQGyhOxFXMNhn8emYnw18TpGaye6tCFG3Clno/fUKSzz3xuOaXEbLWu7P6XEvy7pdzKPtrau8xjcMopZQBQV+KoTKNgMzYsnmmvujfimMYbLkF4l4vh3waD/rXNpFcKlGMRx8BTiTwM5lf4oX5u0MAbk9CY/WTqoFQb6zrlao8MhXUunJKNZgm1twEOlvk9LrPDb0PeC405h83cr7kuxhnf+Nywy+elmQg0XvhhUZG6Cs5hsZ6G8cVHJeMhFUv0Ie4pokJapkr2RxpLygOxJ5wF03nEO41SZFc6S1qdJEghGsRNFpWpY44ONEiEeeeGefZFf9RUf7nwx9AkDMq3LdrqjAESmevOWlDxwS7lH7cgCp94qwnitolKJurb7pSLeMqn+Yh/XgCxRKgv0mNc3dSOhNC5jhs1psX0I8kamkseQYwr2a0VTFVtsfxWqOIPgmBrk+bGqCiPsSzArR9HaBziu10RFS6BwtlpWtCaes3RVTyMHRVMHPuJT+OUsqSUIKfzc027yzDmaW8FQRCuP9P4E0+LdaAjsVtirJYAjpHmom6rT02/uEod13PTX2Y7Doni3A3JNDONM5lpOimEq0/JHIOLcPVXl2Eaf0IgTMqSGK3iaNDVtai/2Qn6INPMdcg=
    - secure: XCbpJNrIo8N4Ik8DCb7OBart8+WgKyKZTdRpWhTfFTheKHxURyr7txu63StT0vvAcJ8lCaKSZFP391j7e2FLBzso5rwExy9RB9gcAitqNM6ot1PXjvdoaFtkBqVhVqA4rEArv69o9+Ayd+3At27JjRIREGkFk63gIVclvbo8bKwTB8GGuc1Td2EKfQCvNJBj4AT8g3k6IhkOcGZCruaphuTutyjC4yyizqlwiEfGFwVGLRAqskRZyTRirFP4jWo2MM3WFNqLCls+pql+LbUMrESpXbnDW5VAlWmZDewR6Tng42nB0evT5EqJ+m3i2Rjgx7gJdcflgpPsvzoOdn2pqixmXE+Zzj0U7AT/B5zUPgWWgWBpkLaGrznYyQK1/tkk+UsseI2BoOzaZ8GjXibm7P5HoX9/MeUDwq33j72WSfspd2OD+R3KXVftWcdsw58FUKH1dzyLn5v7pTQZdH62q8ivDoeNrKma6kC7Avy8X3lbyuSGpeBMuuaOkH0ZqYoayJg66MN90DHihZBJfNkE3wyQXO1f1KdbCL1g5GIO03+q3XRilzMKMv0LbM88uv+H/uS/CLDdZjNQvwEALb86KfIckVCi7R/BnmgfYCdGIKwm86fb0pJ85L3uoJu3UWJl/9DOmLk6ZzsSlLMxbBS6zAb3LSk6YFpXCDMDpDp4Fb4=
    - secure: KXYM74nm1ClIaTT6acYQJBKNje/9kTYT9jzXEGSVCz9MiaLx2bWiUvunZjPDtkj/rhWmyAbCVZOKK3llNHidDPicQ/LliiZbo4+Hll0F9+oAwD1ZvhDRcAKjVF6/nYglbIEcOuyIAiQmIsYWErkYLpz+P+EqISmb6bYoJwmcJnyUbIQsynUR5hyXVmKQQnV6QmAPbT89WbZvvr7XWmNoVUnmQwQmF8lWpfc7JM26FMcOLMko7FcIq2rW0fUrjA0+kg6ii8uYmGY890HNp/8iZ3Gd0+Y+pDqswi0EwxGR0Ovld0UXQGxqN+HqdTHKLLTUVOUlMaBRplgu0XOQEmdVmBHQYD1R4olOS4F1WKnY91WHwvH6rPZ6vF6GxAx/ScwSH+TedSY8CQD9cpdFGZ64TTsmlPr5BB8qQkgL5XA5p5SF1bCoSczXuHlc6n/mefgxc+mdBoXGEb8cKj2VBVKmh6CEg5ozoxzZGpRaL03wbH6QgPZO3mmOR4zacR9UlDJ9pq6sxSzRSS44AclKWJzirBeE9Jwt85zNKcz3xpmFA1VDKidbCrXFeu4lPS6KU+wuXSzabGARNDbY2AqX5KfIwoex53U3HV9Rd1MdJSzKMbNTHU/fSzO1zXppbYIvSZbBH+d4/R6xRffW1EwgDBL3VEpAUE+snaVL3BeWMRgsm6w=
