language: python
python:
  - "3.8"
services:
  - docker

before_install:
  - docker build -t mutants -f Dockerfile-dev .

install:
  - pip install coveralls

script:
  - docker run -v $(pwd):/app/ mutants /bin/bash -c "mypy && pytest --cov=flaskr --cov-report=xml && flake8"

after_success:
  - mv .coverage .coverage.docker
  - coverage combine
  - coveralls
